### ISSUE TITLE
add pre-commit hooks, where the checks are dependent on whether files were changed in the "backend", "ios", or "infra" directories

### ISSUE THREAD

**Issue by trackrat-dev** [trackrat-dev/TrackRat#58]
# Pre-commit Hooks Implementation Proposal

## Overview
This proposal outlines a minimal, directory-specific pre-commit hooks implementation for the TrackRat project based on analysis of the current codebase and existing tooling configurations.

### Existing Pre-commit Configurations
- **Backend**: Comprehensive Python-focused hooks (`.pre-commit-config.yaml`)
  - Black formatting, isort, flake8, mypy, bandit security scanning
- **Infrastructure**: Terraform-focused hooks (`.pre-commit-config.yaml`) 
  - terraform_fmt, terraform_validate, terraform_docs, tflint, checkov security
- **iOS**: Basic validation script (`test_validation.sh`) with xcodebuild
- **Web App**: No linting configuration (vanilla JS/HTML/CSS)

### Project Structure
- `backend/` - Python FastAPI application with comprehensive tooling
- `infra/` - Terraform infrastructure with full validation suite  
- `ios/` - Swift/SwiftUI application with Xcode project
- `webpage/` - Vanilla JavaScript web application

### Root-Level Pre-commit Configuration
Create a single `.pre-commit-config.yaml` at the project root that:
1. **Conditionally runs hooks based on changed files**
2. **Leverages existing configurations in subdirectories**
3. **Provides minimal overhead for contributors**

#### Universal Hooks (Always Run)
```yaml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-yaml
    - id: check-json
```

#### Backend Hooks (when `backend/**` files change)
```yaml
- repo: local
  hooks:
    - id: backend-hooks
      name: Backend pre-commit hooks
      entry: bash -c 'cd backend && pre-commit run --all-files'
      language: system
      files: ^backend/
      pass_filenames: false
```

#### Infrastructure Hooks (when `infra/**` files change)  
```yaml
- repo: local
  hooks:
    - id: infra-hooks
      name: Infrastructure pre-commit hooks
      entry: bash -c 'cd infra && pre-commit run --all-files'
      language: system
      files: ^infra/
      pass_filenames: false
```

#### iOS Hooks (when `ios/**` files change)
```yaml
- repo: local
  hooks:
    - id: ios-build-test
      name: iOS build and syntax validation
      entry: bash -c 'cd ios && ./test_validation.sh'
      language: system
      files: ^ios/.*\.(swift|plist)$
      pass_filenames: false
```

#### Web App Hooks (when `webpage/**` files change)
```yaml
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.44.0
  hooks:
    - id: eslint
      files: ^webpage/.*\.js$
      args: [--fix]
      additional_dependencies:
        - eslint@8.44.0
        
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.0
  hooks:
    - id: prettier
      files: ^webpage/.*\.(html|css|js)$
      exclude: ^webpage/proxy\.py$
```

### 1. **Minimal Overhead** 
- Only runs relevant hooks for changed directories
- Leverages existing configurations without duplication
- No disruption to current development workflows

### 2. **Comprehensive Coverage**
- **Backend**: Full Python toolchain (formatting, linting, type checking, security)
- **Infrastructure**: Complete Terraform validation (format, validate, lint, security)
- **iOS**: Build validation and syntax checking
- **Web**: Basic linting and formatting for maintainability

### 3. **Developer Experience**
- Fast hook execution (only runs for changed files)
- Clear error messages with file-specific context
- Existing workflows remain unchanged

### 4. **CI/CD Integration**
- Hooks can be integrated into GitHub Actions
- Consistent validation across development and CI environments
- Prevents broken commits from reaching main branch

### Phase 1: Core Setup (1-2 hours)
1. Create root `.pre-commit-config.yaml` with universal and directory-specific hooks
2. Update `ios/test_validation.sh` to be more robust and exit cleanly
3. Add basic ESLint/Prettier configuration for webpage
4. Test with sample commits affecting each directory

### Phase 2: Refinement (1 hour)  
1. Optimize hook performance and error messaging
2. Add skip conditions for large file changes
3. Update developer documentation
4. Add GitHub Actions integration

### Phase 3: Documentation (30 minutes)
1. Update README with pre-commit setup instructions
2. Add troubleshooting guide for common issues
3. Document skip patterns for emergency commits

## Developer Setup Instructions

```bash
# Install pre-commit
pip install pre-commit

# Install hooks
pre-commit install

# Test hooks (optional)
pre-commit run --all-files

# Skip hooks for emergency commits (if needed)
git commit --no-verify -m "Emergency fix"
```

### Performance Concerns
- Hooks only run for changed directories
- iOS build hook can be skipped with `SKIP=ios-build-test git commit`
- Large file exclusions prevent timeouts

### Compatibility Issues  
- Fallback to existing directory-specific configurations
- Optional dependencies with clear error messages
- Documentation for troubleshooting common setup issues

### Developer Adoption
- Minimal disruption to existing workflows
- Clear benefits with fast feedback
- Optional enforcement (can be skipped when needed)

## Success Metrics

1. **Reduced CI failures** due to formatting/linting issues
2. **Faster review cycles** with consistent code quality
3. **Developer satisfaction** with clear, fast feedback
4. **Maintainability** through consistent code standards

## Conclusion

This proposal provides a practical, low-overhead solution that respects the existing project structure while adding meaningful quality gates. The directory-specific approach ensures developers only pay the cost for the components they're modifying, making it an efficient addition to the development workflow.

The implementation leverages existing tooling configurations and can be incrementally adopted without disrupting current development practices.
